name: "First Pipeline with Github Actions"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t mateusvictorss/java-ping-api .

      - name: Push Docker Image
        run: docker push mateusvictorss/java-ping-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull mateusvictorss/java-ping-api:latest

      - name: Run Docker Container
        run: docker run -d -p 80:8080 --name java-ping-api mateusvictorss/java-ping-api
